name       : python-cppy
version    : 1.2.0
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/c/cppy/cppy-1.2.0.tar.gz : 95e8862e4f826c3f2a6b7b658333b162f80cbe9f943aa0d0a7a6b2ef850aeffc
homepage   : https://github.com/nucleic/cppy
license    : BSD-3-Clause
component  : programming.python
summary    : A collection of C++ headers which make it easier to write Python C extension modules
description: |
    A small C++ header library which makes it easier to write Python extension modules. The primary feature is a PyObject smart pointer which automatically handles reference counting and provides convenience methods for performing common object operations.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-pytest
    - python-setuptools-scm
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=$version
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
