name       : python-cppy
version    : 1.1.0
release    : 2
source     :
    - https://github.com/nucleic/cppy/archive/1.1.0.tar.gz : 40a9672df1ec2d7f0b54f70e574101f42131c0f5e47980769f68085e728a4934
homepage   : https://github.com/nucleic/cppy
license    : BSD-3-Clause
component  : programming.python
summary    : A collection of C++ headers which make it easier to write Python C extension modules
description: |
    A small C++ header library which makes it easier to write Python extension modules. The primary feature is a PyObject smart pointer which automatically handles reference counting and provides convenience methods for performing common object operations.
builddeps  :
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
